print("Water Fountain")
water = int(input("Enter number of water fountains: "))
water_location = str(input("Enter the location of them: "))
water_condition = str(input("Enter the condition of them: "))

print("Restroom")
restrooms = int(input("Enter number of restrooms: "))
restrooms_location = str(input("Enter the location of them: "))
restrooms_condition = str(input("Enter the condition of them: "))

print("Common Areas")
common_areas = int(input("Enter number of common areas: "))
common_areas_location = str(input("Enter the location of them: "))
common_areas_condition = str(input("Enter the condition of them: "))

print("Change Rooms")
change_rooms = int(input("Enter number of change rooms: "))
change_rooms_location = str(input("Enter the location of them: "))
change_rooms_condition = str(input("Enter the condition of them: "))

print("Gyms")
gyms = int(input("Enter number of gyms: "))
gyms_location = str(input("Enter the location of them: "))
gyms_condition = str(input("Enter the condition of them: "))

print("Classrooms")
classrooms = int(input("Enter number of classrooms: "))

print("Water Fountain")
print(f" - The number of water fountains are {water}")
print(f" - Locations: {water_location}")
print(f" - Condition: {water_condition}")
print("Restroom")
print(f" - The number of restrooms are {restrooms}")
print(f" - Locations: {restrooms_location}")
print(f" - Condition: {restrooms_condition}")
print("Common Areas")
print(f" - The number of common areas are {common_areas}")
print(f" - Locations: {common_areas_location}")
print(f" - Condition: {common_areas_condition}")
print("Change Rooms")
print(f" - The number of common areas are {change_rooms}")
print(f" - Locations: {change_rooms_location}")
print(f" - Condition: {change_rooms_condition}")
print("Gyms")
print(f" - The number of common areas are {gyms}")
print(f" - Locations: {gyms_location}")
print(f" - Condition: {gyms_condition}")
print("Classrooms")
print(f" - Number of water fountains per classroom: {water/classrooms}")
print(f" - Number of restrooms per classroom: {restrooms/classrooms}")